export const CREATE_PHOTO = "CREATE_PHOTO";
export const UPDATE_PHOTO = "UPDATE_PHOTO";
export const DELETE_PHOTO = "DELETE_PHOTO";

export const CREATE_COLLECTION = "CREATE_COLLECTIONS";
export const UPDATE_COLLECTION = "UPDATE_COLLECTIONS";
export const DELETE_COLLECTION = "DELETE_COLLECTIONS";

export const CREATE_FAVORITE = "CREATE_FAVORITE";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const DELETE_FAVORITE = "DELETE_FAVORITE";
